version: '3.8'

services:
  risk-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monte-carlo-risk-engine
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=4
      - FASTAPI_ENV=production
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - risk-engine-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: risk-engine-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - risk-engine
    networks:
      - risk-engine-network
    restart: unless-stopped
    profiles:
      - production

networks:
  risk-engine-network:
    driver: bridge

volumes:
  logs:
    driver: local